name: Keepalive Workflow
on:
  schedule:
    - cron: "0 16 * * SUN" # 北京时间 0 点（UTC 16 点）
  workflow_dispatch: # 支持手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Keepalive
        uses: efrecon/gh-action-keepalive@main
