name: Keepalive Workflow
on:
  schedule:
    - cron: "0 16 15 * *" # 北京时间 0 点（UTC 16 点）每月 15 号
  workflow_dispatch: # 支持手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Keepalive
        uses: efrecon/gh-action-keepalive@main
        with:
          # 距离上次提交超过45天才执行刷新，避免频繁操作
          # days_threshold: 45
          # api模式：不生成commit；设为false则使用空commit
          use_api: true
